### ISSUE TITLE
[sample-issue] I can't see song titles

### ISSUE THREAD

**Issue by dermidgen** [dermidgen/hiphonix#1]
When I'm in my library I can't see the titles for the songs

**Comment by jgaud16** [comment]
1) Standard Features in music player (Add song to queue, Add playlist to queue,Save Queue to Playlist, Shuffle Songs in Queue, Randomize Songs in Queue, Start Play, Stop Play, Show Time Progress into Track .. etc)  are listed only for completeness

**Comment by jgaud16** [comment]
Note : jgaud is Joel
2) Add 2 levels of quality in settings (High and Low) in user view.  Expose multiple quality settings of DAC in debug version

**Comment by jgaud16** [comment]
3) This is for Project progress :  Need for next release :  GUI Method to show detection and connection into Wireless Network - This is critical for QA testing

**Comment by jgaud16** [comment]
4) This is for Project progress :  Need for next release :  Simple GUI Method to show initial phases of Song Source Discovery (USB and some Internet Radio would be great) - This is critical for QA testing

**Comment by jgaud16** [comment]
5) This is for Project progress :  Need for next release :  GUI Method to start and stop 1 song ,that will be placed hard-coded from first song on USB media (from USB Discovery Phase) into MPD queue.  When started the song will run in a loop forever until stopped  - This would be a good QA testing of streaming reliability in this release
